### ISSUE TITLE
Interactive mode?

### ISSUE THREAD

**Issue by rexroni** [aaronryank/rubiks-cube#8]
It would be really cool if there was an interactive mode that printed the cube state everytime that input was requested from the user.

In fact, I just wrote such a patch, and it is in a pull request I will submit shortly.

**Comment by aaronryank** [comment]
I have this, it's the visualizer. It's temporarily broken due to output file restrictions.

**Comment by rexroni** [comment]
Ok cool.  Yes, I noticed it was broken, but I thought since it tried to include `rubicks.h` which was in the `old` folder that the intention was for the visualizer to be phased out.  Since you already have this feature, I will remove my interactive mode from the merge request.

Does the visualizer work like an interactive shell?  If not, is there any intention of having an interactive shell?  I would be happy to work on that if it would be helpful.

I think this is like the coolest esolang ever!

**Comment by aaronryank** [comment]
Sounds good; the other commits seem to be fine so I'll likely merge them. I haven't updated the visualizer in forever; not really sure why that happened...

The visualizer works like an interactive shell, yes, but it doesn't have any commands such as output and input or loops or anything; it can do `RLUDFB`. (I plan on adding loops once development on Cubically has calmed down; it sorta spiked last week.)

And thanks, glad you like it! I like it too, and I created it because I couldn't find another language with a similar memory model.. I think it's painful and tedious, yet pretty useful.

**Comment by aaronryank** [comment]
I'll close this issue when the visualizer is fixed.

**Comment by aaronryank** [comment]
Visualizer is fixed.
